from __future__ import annotations

from typing import TYPE_CHECKING

from BaseClasses import Item, ItemClassification
from worlds.apquest.items import DEFAULT_ITEM_CLASSIFICATIONS, ITEM_NAME_TO_ID

if TYPE_CHECKING:
    from .world import MMLWorld

ITEM_NAME_TO_ID = {
    "Nothing":                              0x00FF,
    "Power Raiser":                         0x020D,
    "Power Stream":                         0x0211,
    "Blaster Unit R":                       0x0212,
    "Buster Unit Omega":                    0x0213,
    "Rapid Striker":                        0x0217,
    "Buster Unit":                          0x021E,
    "Rapid Fire":                           0x021F,
    "Lake Jyun Sub-Gate Starter Key 1":     0x0231,
    "Lake Jyun Sub-Gate Starter Key 2":     0x0232,
    "Lake Jyun Sub-Gate Starter Key 3":     0x0233,
    "Clozer Woods Sub-Gate Key 1":          0x0234,
    "Clozer Woods Sub-Gate Key 2":          0x0235,
    "Clozer Woods Sub-Gate Key 3":          0x0236,
    "Watcher' Key":                         0x0237,
    "Sleeper' Key":                         0x0238,
    "Dreamer' Key":                         0x0239,
    "Old Bone":                             0x024B,
    "Old Doll":                             0x024D,
    "Antique Bell":                         0x024E,
    "Shiny Object":                         0x0250,
    "Old Shield":                           0x0251,
    "Shiny Red Stone":                      0x0252,
    "Ring":                                 0x0256,
    "Cannon Kit":                           0x0259,
    "Grenade Kit":                          0x025A,
    "Blumebear Parts":                      0x025B,
    "Broken Motor":                         0x025E,
    "Broken Propeller":                     0x025F,
    "Broken Cleaner":                       0x0260,
    "Bomb Schematic":                       0x0261,
    "Blunted Drill":                        0x0262,
    "Guidance Unit":                        0x0263,
    "Pen Light":                            0x0265,
    "Old Launcher":                         0x0266,
    "Ancient Book":                         0x0267,
    "Weapon Plans":                         0x026A,
    "Spring Set":                           0x026C,
    "Safety Helmet":                        0x026D,
    "Rollerboard":                          0x026E,
    "Old Hoverjets":                        0x026F,
    "Joint Plug":                           0x0270,
    "Main Core Shard":                      0x0272,
    "Rapidfire Barrel":                     0x0274,
    "Gatling Part":                         0x0277,
    "Autofire Barrel":                      0x0279,
    "Generator Part":                       0x027A,
    "Target Sensor":                        0x027B,
    "Tele-lens":                            0x027C,
    "10 Zenny":                             0x800A,
    "20 Zenny":                             0x8014,
    "30 Zenny":                             0x801E,
    "50 Zenny":                             0x8032,
    "100 Zenny":                            0x8064,
    "200 Zenny":                            0x80C8,
    "220 Zenny":                            0x80DC,
    "300 Zenny":                            0x812C,
    "450 Zenny":                            0x81C2,
    "560 Zenny":                            0x8230,
    "660 Zenny":                            0x8294,
    "780 Zenny":                            0x830C,
    "820 Zenny":                            0x8334,
    "920 Zenny":                            0x8398,
    "1180 Zenny":                           0x849C,
    "1200 Zenny":                           0x84B0,
    "1240 Zenny":                           0x84D8,
    "1510 Zenny":                           0x85E6,
    "1620 Zenny":                           0x8654,
    "1780 Zenny":                           0x86F4,
    "1840 Zenny":                           0x8730,
    "2170 Zenny":                           0x887A,
    "2280 Zenny":                           0x88E8,
    "2300 Zenny":                           0x88FC,
    "2600 Zenny":                           0x8A28,
    "2840 Zenny":                           0x8B18,
    "4520 Zenny":                           0x91A8,
    "5130 Zenny":                           0x940A,
    "5600 Zenny":                           0x95E0,
    "9240 Zenny":                           0xA418,
    "10000 Zenny":                          0xA710
}

#TODO map every item to a classification of progressive,useful,filler,etc
DEFAULT_ITEM_CLASSIFICATIONS = {
    "Nothing":                              ItemClassification.filler, 
    "Power Raiser":                         ItemClassification.filler, 
    "Power Stream":                         ItemClassification.filler, 
    "Blaster Unit R":                       ItemClassification.filler, 
    "Buster Unit Omega":                    ItemClassification.filler, 
    "Rapid Striker":                        ItemClassification.filler, 
    "Buster Unit":                          ItemClassification.filler, 
    "Rapid Fire":                           ItemClassification.filler, 
    "Lake Jyun Sub-Gate Starter Key 1":     ItemClassification.filler, 
    "Lake Jyun Sub-Gate Starter Key 2":     ItemClassification.filler, 
    "Lake Jyun Sub-Gate Starter Key 3":     ItemClassification.filler, 
    "Clozer Woods Sub-Gate Key 1":          ItemClassification.filler, 
    "Clozer Woods Sub-Gate Key 2":          ItemClassification.filler, 
    "Clozer Woods Sub-Gate Key 3":          ItemClassification.filler, 
    "Watcher' Key":                         ItemClassification.filler, 
    "Sleeper' Key":                         ItemClassification.filler, 
    "Dreamer' Key":                         ItemClassification.filler, 
    "Old Bone":                             ItemClassification.filler, 
    "Old Doll":                             ItemClassification.filler, 
    "Antique Bell":                         ItemClassification.filler, 
    "Shiny Object":                         ItemClassification.filler, 
    "Old Shield":                           ItemClassification.filler, 
    "Shiny Red Stone":                      ItemClassification.filler, 
    "Ring":                                 ItemClassification.filler, 
    "Cannon Kit":                           ItemClassification.filler, 
    "Grenade Kit":                          ItemClassification.filler, 
    "Blumebear Parts":                      ItemClassification.filler, 
    "Broken Motor":                         ItemClassification.filler, 
    "Broken Propeller":                     ItemClassification.filler, 
    "Broken Cleaner":                       ItemClassification.filler, 
    "Bomb Schematic":                       ItemClassification.filler, 
    "Blunted Drill":                        ItemClassification.filler, 
    "Guidance Unit":                        ItemClassification.filler, 
    "Pen Light":                            ItemClassification.filler, 
    "Old Launcher":                         ItemClassification.filler, 
    "Ancient Book":                         ItemClassification.filler, 
    "Weapon Plans":                         ItemClassification.filler, 
    "Spring Set":                           ItemClassification.filler, 
    "Safety Helmet":                        ItemClassification.filler, 
    "Rollerboard":                          ItemClassification.filler, 
    "Old Hoverjets":                        ItemClassification.filler, 
    "Joint Plug":                           ItemClassification.filler, 
    "Main Core Shard":                      ItemClassification.filler, 
    "Rapidfire Barrel":                     ItemClassification.filler, 
    "Gatling Part":                         ItemClassification.filler, 
    "Autofire Barrel":                      ItemClassification.filler, 
    "Generator Part":                       ItemClassification.filler, 
    "Target Sensor":                        ItemClassification.filler, 
    "Tele-lens":                            ItemClassification.filler, 
    "10 Zenny":                             ItemClassification.filler, 
    "20 Zenny":                             ItemClassification.filler, 
    "30 Zenny":                             ItemClassification.filler, 
    "50 Zenny":                             ItemClassification.filler, 
    "100 Zenny":                            ItemClassification.filler, 
    "200 Zenny":                            ItemClassification.filler, 
    "220 Zenny":                            ItemClassification.filler, 
    "300 Zenny":                            ItemClassification.filler, 
    "450 Zenny":                            ItemClassification.filler, 
    "560 Zenny":                            ItemClassification.filler, 
    "660 Zenny":                            ItemClassification.filler, 
    "780 Zenny":                            ItemClassification.filler, 
    "820 Zenny":                            ItemClassification.filler, 
    "920 Zenny":                            ItemClassification.filler, 
    "1180 Zenny":                           ItemClassification.filler, 
    "1200 Zenny":                           ItemClassification.filler, 
    "1240 Zenny":                           ItemClassification.filler, 
    "1510 Zenny":                           ItemClassification.filler, 
    "1620 Zenny":                           ItemClassification.filler, 
    "1780 Zenny":                           ItemClassification.filler, 
    "1840 Zenny":                           ItemClassification.filler, 
    "2170 Zenny":                           ItemClassification.filler, 
    "2280 Zenny":                           ItemClassification.filler, 
    "2300 Zenny":                           ItemClassification.filler, 
    "2600 Zenny":                           ItemClassification.filler, 
    "2840 Zenny":                           ItemClassification.filler, 
    "4520 Zenny":                           ItemClassification.filler, 
    "5130 Zenny":                           ItemClassification.filler, 
    "5600 Zenny":                           ItemClassification.filler, 
    "9240 Zenny":                           ItemClassification.filler, 
    "10000 Zenny":                          ItemClassification.filler
}

class MMLItem(Item):
    game = "Mega Man Legends"

def get_random_filler_item_name(world: MMLWorld) -> str:
    if world.random.randint(0, 99) < world.options.trap_chance:
        return "Nothing"
    return "100 Zenny"

def create_item_with_correct_classification(world: MMLWorld, name: str) -> MMLItem:
    classification = DEFAULT_ITEM_CLASSIFICATIONS[name]
    return MMLItem(name, classification, ITEM_NAME_TO_ID[name], world.player)

def create_all_items(world: MMLWorld) -> None:
    #TODO
    pass