using MMLAP.Models
using System.Collections.Generic;
namespace MMLAP
{
    public class Helpers
    {
        public static Dictionary<ushort, LevelData> GetLevelDataDict()
        {
            Dictionary<ushort, LevelData> levelDataDict = new Dictionary<ushort, LevelData>();
            levelDataDict.Add(0x0000, new LevelData("Ocean Tower", "Intro cutscene", 0x00, 0x00));
            levelDataDict.Add(0x0001, new LevelData("Ocean Tower", "Room 1 (Entrance)", 0x00, 0x01));
            levelDataDict.Add(0x0002, new LevelData("Ocean Tower", "Room 2", 0x00, 0x02));
            levelDataDict.Add(0x0003, new LevelData("Ocean Tower", "Room 3 (Boss)", 0x00, 0x03));
            levelDataDict.Add(0x0004, new LevelData("Ocean Tower", "Outdoor Cutscene", 0x00, 0x04));
            levelDataDict.Add(0x0005, new LevelData("Ocean Tower", "Back To Title Screen", 0x00, 0x05));
            levelDataDict.Add(0x0006, new LevelData("Ocean Tower", "Empty?", 0x00, 0x06));
            levelDataDict.Add(0x0100, new LevelData("Opening Text Cutscene", "Scrolling Text", 0x01, 0x00));
            levelDataDict.Add(0x0200, new LevelData("Crash Cutscene", "Cutscene", 0x02, 0x00));
            levelDataDict.Add(0x0300, new LevelData("Cardon Forest (Flutter Broken)", "Near ruin entrance", 0x03, 0x00));
            levelDataDict.Add(0x0301, new LevelData("Cardon Forest (Flutter Broken)", "Crash Site", 0x03, 0x01));
            levelDataDict.Add(0x0302, new LevelData("Cardon Forest (Flutter Broken)", "City Entrance", 0x03, 0x02));
            levelDataDict.Add(0x0303, new LevelData("Cardon Forest (Flutter Broken)", "Unknown (floating model)", 0x03, 0x03));
            levelDataDict.Add(0x0304, new LevelData("Cardon Forest (Flutter Broken)", "Unknown (floating model)", 0x03, 0x04));
            levelDataDict.Add(0x0305, new LevelData("Cardon Forest (Flutter Broken)", "Barell's Room", 0x03, 0x05));
            levelDataDict.Add(0x0306, new LevelData("Cardon Forest (Flutter Broken)", "Roll's Room (no Roll)", 0x03, 0x06));
            levelDataDict.Add(0x0307, new LevelData("Cardon Forest (Flutter Broken)", "Flutter", 0x03, 0x07));
            levelDataDict.Add(0x0308, new LevelData("Cardon Forest (Flutter Broken)", "Mega Man's Room", 0x03, 0x08));
            levelDataDict.Add(0x0400, new LevelData("Apple Market", "Apple Market", 0x04, 0x00));
            levelDataDict.Add(0x0401, new LevelData("Apple Market", "Junk Shop", 0x04, 0x01));
            levelDataDict.Add(0x0402, new LevelData("Apple Market", "Electronics Shop", 0x04, 0x02));
            levelDataDict.Add(0x0403, new LevelData("Apple Market", "Hip Bone", 0x04, 0x03));
            levelDataDict.Add(0x0404, new LevelData("Apple Market", "Tailor Chinos", 0x04, 0x04));
            levelDataDict.Add(0x0405, new LevelData("Apple Market", "Record Shop", 0x04, 0x05));
            levelDataDict.Add(0x0500, new LevelData("Downtown", "Downtown", 0x05, 0x00));
            levelDataDict.Add(0x0501, new LevelData("Downtown", "(no music, no sub-city, missing door texture)", 0x05, 0x01));
            levelDataDict.Add(0x0502, new LevelData("Downtown", "Library", 0x05, 0x02));
            levelDataDict.Add(0x0503, new LevelData("Downtown", "Tron's Cockpit", 0x05, 0x03));
            levelDataDict.Add(0x0504, new LevelData("Downtown", "Stripe Burger", 0x05, 0x04));
            levelDataDict.Add(0x0600, new LevelData("City Hall", "Outdoors", 0x06, 0x00));
            levelDataDict.Add(0x0601, new LevelData("City Hall", "Amelia's Office", 0x06, 0x01));
            levelDataDict.Add(0x0602, new LevelData("City Hall", "Outdoors (no music, cars, or people)", 0x06, 0x02));
            levelDataDict.Add(0x0603, new LevelData("City Hall", "Teisel's Room", 0x06, 0x03));
            levelDataDict.Add(0x0604, new LevelData("City Hall", "Amelia's Office (wrecked)", 0x06, 0x04));
            levelDataDict.Add(0x0700, new LevelData("Gesselschaft Interior", "Empty?", 0x07, 0x00));
            levelDataDict.Add(0x0701, new LevelData("Gesselschaft Interior", "Engine Room", 0x07, 0x01));
            levelDataDict.Add(0x0702, new LevelData("Gesselschaft Interior", "Hallway", 0x07, 0x02));
            levelDataDict.Add(0x0703, new LevelData("Gesselschaft Interior", "Kitchen", 0x07, 0x03));
            levelDataDict.Add(0x0704, new LevelData("Gesselschaft Interior", "HQ", 0x07, 0x04));
            levelDataDict.Add(0x0705, new LevelData("Gesselschaft Interior", "First Meeting Room Cutscene", 0x07, 0x05));
            levelDataDict.Add(0x0706, new LevelData("Gesselschaft Interior", "Meeting Room", 0x07, 0x06));
            levelDataDict.Add(0x0707, new LevelData("Gesselschaft Interior", "Empty?", 0x07, 0x07));
            levelDataDict.Add(0x0800, new LevelData("Uptown", "Uptown", 0x08, 0x00));
            levelDataDict.Add(0x0801, new LevelData("Uptown", "Hospital", 0x08, 0x01));
            levelDataDict.Add(0x0802, new LevelData("Uptown", "TV Station", 0x08, 0x02));
            levelDataDict.Add(0x0803, new LevelData("Uptown", "Beast Hunter game", 0x08, 0x03));
            levelDataDict.Add(0x0804, new LevelData("Uptown", "Balloon Game", 0x08, 0x04));
            levelDataDict.Add(0x0805, new LevelData("Uptown", "Ira's Room", 0x08, 0x05));
            levelDataDict.Add(0x0900, new LevelData("Underground Ruins", "Room 1 (Junk Store Man Area)", 0x09, 0x00));
            levelDataDict.Add(0x0901, new LevelData("Underground Ruins", "Room 2", 0x09, 0x01));
            levelDataDict.Add(0x0902, new LevelData("Underground Ruins", "Room 3 (Sewer)", 0x09, 0x02));
            levelDataDict.Add(0x0903, new LevelData("Underground Ruins", "Room 4", 0x09, 0x03));
            levelDataDict.Add(0x0904, new LevelData("Underground Ruins", "Room 5", 0x09, 0x04));
            levelDataDict.Add(0x0905, new LevelData("Underground Ruins", "Room 6", 0x09, 0x05));
            levelDataDict.Add(0x0906, new LevelData("Underground Ruins", "Room 7", 0x09, 0x06));
            levelDataDict.Add(0x0907, new LevelData("Underground Ruins", "Room 8", 0x09, 0x07));
            levelDataDict.Add(0x0908, new LevelData("Underground Ruins", "Room 9", 0x09, 0x08));
            levelDataDict.Add(0x0A00, new LevelData("Clozer Woods (Tiesel)", "Tiesel Area", 0x0A, 0x00));
            levelDataDict.Add(0x0B00, new LevelData("Lake Jyun", "Inside Bonne Robot", 0x0B, 0x00));
            levelDataDict.Add(0x0B01, new LevelData("Lake Jyun", "???", 0x0B, 0x01));
            levelDataDict.Add(0x0B02, new LevelData("Lake Jyun", "On the Lake", 0x0B, 0x02));
            levelDataDict.Add(0x0B03, new LevelData("Lake Jyun", "Side River", 0x0B, 0x03));
            levelDataDict.Add(0x0B04, new LevelData("Lake Jyun", "Inside Bonne Robot", 0x0B, 0x04));
            levelDataDict.Add(0x0B05, new LevelData("Lake Jyun", "Empty?", 0x0B, 0x05));
            levelDataDict.Add(0x0B06, new LevelData("Lake Jyun", "Door Opening Mechanism", 0x0B, 0x06));
            levelDataDict.Add(0x0B07, new LevelData("Lake Jyun", "Subgate With Open Door", 0x0B, 0x07));
            levelDataDict.Add(0x0C00, new LevelData("Outside Cardon Forest Subgate", "Outside", 0x0C, 0x00));
            levelDataDict.Add(0x0C01, new LevelData("Outside Cardon Forest Subgate", "Door Opening Mechanism", 0x0C, 0x01));
            levelDataDict.Add(0x0C02, new LevelData("Outside Cardon Forest Subgate", "Subgate With Open Door", 0x0C, 0x02));
            levelDataDict.Add(0x0C03, new LevelData("Outside Cardon Forest Subgate", "Small Piece of Ground", 0x0C, 0x03));
            levelDataDict.Add(0x0D00, new LevelData("Wily's Boat", "Walkway", 0x0D, 0x00));
            levelDataDict.Add(0x0D01, new LevelData("Wily's Boat", "Inside", 0x0D, 0x01));
            levelDataDict.Add(0x0D02, new LevelData("Wily's Boat", "Boat Area", 0x0D, 0x02));
            levelDataDict.Add(0x0D03, new LevelData("Wily's Boat", "Inside The Boat", 0x0D, 0x03));
            levelDataDict.Add(0x0D04, new LevelData("Wily's Boat", "Walkway (no box or woman)", 0x0D, 0x04));
            levelDataDict.Add(0x0D05, new LevelData("Wily's Boat", "Walkway (no box, woman, or boat)", 0x0D, 0x05));
            levelDataDict.Add(0x0E00, new LevelData("Cardon Forest Sub-gate", "Room 1", 0x0E, 0x00));
            levelDataDict.Add(0x0E01, new LevelData("Cardon Forest Sub-gate", "Room 1", 0x0E, 0x01));
            levelDataDict.Add(0x0E02, new LevelData("Cardon Forest Sub-gate", "Room 1", 0x0E, 0x02));
            levelDataDict.Add(0x0F00, new LevelData("City Hall (Indoors)", "Police Station", 0x0F, 0x00));
            levelDataDict.Add(0x0F01, new LevelData("City Hall (Indoors)", "Inspector's Office", 0x0F, 0x01));
            levelDataDict.Add(0x0F02, new LevelData("City Hall (Indoors)", "City Hall 1st Floor", 0x0F, 0x02));
            levelDataDict.Add(0x0F03, new LevelData("City Hall (Indoors)", "Bank", 0x0F, 0x03));
            levelDataDict.Add(0x1000, new LevelData("Yass Plains", "Yass Plains Outdoors", 0x10, 0x00));
            levelDataDict.Add(0x1001, new LevelData("Yass Plains", "Hideout Stage 1", 0x10, 0x01));
            levelDataDict.Add(0x1002, new LevelData("Yass Plains", "Hideout Stage 2", 0x10, 0x02));
            levelDataDict.Add(0x1003, new LevelData("Yass Plains", "Hideout Stage 3", 0x10, 0x03));
            levelDataDict.Add(0x1004, new LevelData("Yass Plains", "Empty House", 0x10, 0x04));
            levelDataDict.Add(0x1005, new LevelData("Yass Plains", "Junk Shop House", 0x10, 0x05));
            levelDataDict.Add(0x1100, new LevelData("Clozer Woods With Bridge", "Clozer Woods With Bridge", 0x11, 0x00));
            levelDataDict.Add(0x1200, new LevelData("Outside Main Gate", "Outside Main Gate", 0x12, 0x00));
            levelDataDict.Add(0x1300, new LevelData("Clozer Woods Sub-Gate", "Room 1 (Entrance)", 0x13, 0x00));
            levelDataDict.Add(0x1301, new LevelData("Clozer Woods Sub-Gate", "Room 2", 0x13, 0x01));
            levelDataDict.Add(0x1302, new LevelData("Clozer Woods Sub-Gate", "Room 3 (Key Room)", 0x13, 0x02));
            levelDataDict.Add(0x1303, new LevelData("Clozer Woods Sub-Gate", "Room 4", 0x13, 0x03));
            levelDataDict.Add(0x1304, new LevelData("Clozer Woods Sub-Gate", "Room 5", 0x13, 0x04));
            levelDataDict.Add(0x1305, new LevelData("Clozer Woods Sub-Gate", "Room 6", 0x13, 0x05));
            levelDataDict.Add(0x1306, new LevelData("Clozer Woods Sub-Gate", "Room 7", 0x13, 0x06));
            levelDataDict.Add(0x1307, new LevelData("Clozer Woods Sub-Gate", "Room 8", 0x13, 0x07));
            levelDataDict.Add(0x1308, new LevelData("Clozer Woods Sub-Gate", "Room 9 (Generator)", 0x13, 0x08));
            levelDataDict.Add(0x1309, new LevelData("Clozer Woods Sub-Gate", "Room 10", 0x13, 0x09));
            levelDataDict.Add(0x130A, new LevelData("Clozer Woods Sub-Gate", "Flutter Barell's Room", 0x13, 0x0A));
            levelDataDict.Add(0x130B, new LevelData("Clozer Woods Sub-Gate", "Flutter Roll's Room", 0x13, 0x0B));
            levelDataDict.Add(0x130C, new LevelData("Clozer Woods Sub-Gate", "Flutter Lobby", 0x13, 0x0C));
            levelDataDict.Add(0x130D, new LevelData("Clozer Woods Sub-Gate", "Flutter Mega Man's Room", 0x13, 0x0D));
            levelDataDict.Add(0x1400, new LevelData("Lake Jyun Sub-Gate", "Room 1 (Entrance)", 0x14, 0x00));
            levelDataDict.Add(0x1401, new LevelData("Lake Jyun Sub-Gate", "Room 2", 0x14, 0x01));
            levelDataDict.Add(0x1402, new LevelData("Lake Jyun Sub-Gate", "Room 3", 0x14, 0x02));
            levelDataDict.Add(0x1403, new LevelData("Lake Jyun Sub-Gate", "Room 4 ", 0x14, 0x03));
            levelDataDict.Add(0x1404, new LevelData("Lake Jyun Sub-Gate", "Refractor Room", 0x14, 0x04));
            levelDataDict.Add(0x1500, new LevelData("Bonne Ending Boat", "Boat Interior", 0x15, 0x00));
            levelDataDict.Add(0x1501, new LevelData("Bonne Ending Boat", "Ocean", 0x15, 0x01));
            levelDataDict.Add(0x1600, new LevelData("Flutter To Subgate Cutscene", "Cutscene", 0x16, 0x00));
            levelDataDict.Add(0x1601, new LevelData("Flutter To Subgate Cutscene", "Flutter Bridge", 0x16, 0x01));
            levelDataDict.Add(0x1602, new LevelData("Flutter To Subgate Cutscene", "Return Cutscene", 0x16, 0x02));
            levelDataDict.Add(0x1700, new LevelData("Gesselschaft Battle", "Small Bridge", 0x17, 0x00));
            levelDataDict.Add(0x1701, new LevelData("Gesselschaft Battle", "Flutter Bridge", 0x17, 0x01));
            levelDataDict.Add(0x1702, new LevelData("Gesselschaft Battle", "Gesselschaft HQ", 0x17, 0x02));
            levelDataDict.Add(0x1703, new LevelData("Gesselschaft Battle", "Scrolling Clouds", 0x17, 0x03));
            levelDataDict.Add(0x1800, new LevelData("Flutter Takeoff", "Cardon Forest with no Flutter (Yasmar Woods)", 0x18, 0x00));
            levelDataDict.Add(0x1801, new LevelData("Flutter Takeoff", "Flutter Engine Room", 0x18, 0x01));
            levelDataDict.Add(0x1802, new LevelData("Flutter Takeoff", "Glowing Refractor", 0x18, 0x02));
            levelDataDict.Add(0x1900, new LevelData("Old City", "Old City (no dogs, weapons usable)", 0x19, 0x00));
            levelDataDict.Add(0x1901, new LevelData("Old City", "Bonne's Warehouse", 0x19, 0x01));
            levelDataDict.Add(0x1902, new LevelData("Old City", "Power Plant", 0x19, 0x02));
            levelDataDict.Add(0x1903, new LevelData("Old City", "Old City (dogs, no weapons)", 0x19, 0x03));
            levelDataDict.Add(0x1A00, new LevelData("Main Gate", "Second Area (where you unlock the sub-cities)", 0x1A, 0x00));
            levelDataDict.Add(0x1A01, new LevelData("Main Gate", "Third Area (Watcher, Sleeper, Dreamer doors)", 0x1A, 0x01));
            levelDataDict.Add(0x1A02, new LevelData("Main Gate", "Final Area", 0x1A, 0x02));
            levelDataDict.Add(0x1A03, new LevelData("Main Gate", "First Area 1", 0x1A, 0x03));
            levelDataDict.Add(0x1A04, new LevelData("Main Gate", "First Area 2", 0x1A, 0x04));
            levelDataDict.Add(0x1A05, new LevelData("Main Gate", "First Area 3", 0x1A, 0x05));
            levelDataDict.Add(0x1A06, new LevelData("Main Gate", "First Area 4", 0x1A, 0x06));
            levelDataDict.Add(0x1A07, new LevelData("Main Gate", "First Area 5", 0x1A, 0x07));
            levelDataDict.Add(0x1A08, new LevelData("Main Gate", "First Area 6", 0x1A, 0x08));
            levelDataDict.Add(0x1A09, new LevelData("Main Gate", "First Area 7 (Entrance)", 0x1A, 0x09));
            levelDataDict.Add(0x1A0A, new LevelData("Main Gate", "Tiny Kattelox", 0x1A, 0x0A));
            levelDataDict.Add(0x1A0B, new LevelData("Main Gate", "Juno Wall", 0x1A, 0x0B));
            levelDataDict.Add(0x1A0C, new LevelData("Main Gate", "Amelia's Office (simplified)", 0x1A, 0x0C));
            levelDataDict.Add(0x1A0D, new LevelData("Main Gate", "Downtown (simplified)", 0x1A, 0x0D));
            levelDataDict.Add(0x1A0E, new LevelData("Main Gate", "Empty?", 0x1A, 0x0E));
            levelDataDict.Add(0x1A0F, new LevelData("Main Gate", "Juno's Room Without Door", 0x1A, 0x0F));
            levelDataDict.Add(0x1A10, new LevelData("Main Gate", "Unknown (textures?)", 0x1A, 0x10));
            levelDataDict.Add(0x1B00, new LevelData("Cardon Forest (Flutter Fixed)", "Near ruin entrance", 0x1B, 0x00));
            levelDataDict.Add(0x1B01, new LevelData("Cardon Forest (Flutter Fixed)", "Crash Site", 0x1B, 0x01));
            levelDataDict.Add(0x1B02, new LevelData("Cardon Forest (Flutter Fixed)", "City Entrance", 0x1B, 0x02));
            levelDataDict.Add(0x1B03, new LevelData("Cardon Forest (Flutter Fixed)", "Unknown (floating model)", 0x1B, 0x03));
            levelDataDict.Add(0x1B04, new LevelData("Cardon Forest (Flutter Fixed)", "Unknown (floating model)", 0x1B, 0x04));
            levelDataDict.Add(0x1B05, new LevelData("Cardon Forest (Flutter Fixed)", "Barell's Room", 0x1B, 0x05));
            levelDataDict.Add(0x1B06, new LevelData("Cardon Forest (Flutter Fixed)", "Roll's Room", 0x1B, 0x06));
            levelDataDict.Add(0x1B07, new LevelData("Cardon Forest (Flutter Fixed)", "Flutter Lobby", 0x1B, 0x07));
            levelDataDict.Add(0x1B08, new LevelData("Cardon Forest (Flutter Fixed)", "Mega Man's Room", 0x1B, 0x08));
            levelDataDict.Add(0x1C00, new LevelData("Museum", "First Floor", 0x1C, 0x00));
            levelDataDict.Add(0x1C01, new LevelData("Museum", "Second Floor", 0x1C, 0x01));
            levelDataDict.Add(0x1D00, new LevelData("Sub-Cities", "Watcher Sub-City", 0x1D, 0x00));
            levelDataDict.Add(0x1D01, new LevelData("Sub-Cities", "Sleeper Sub-City", 0x1D, 0x01));
            levelDataDict.Add(0x1D02, new LevelData("Sub-Cities", "Dreamer Sub-City", 0x1D, 0x02));
            levelDataDict.Add(0x1D03, new LevelData("Sub-Cities", "Watcher Chest Room", 0x1D, 0x03));
            levelDataDict.Add(0x1D04, new LevelData("Sub-Cities", "Sleeper Chest Room", 0x1D, 0x04));
            levelDataDict.Add(0x1D05, new LevelData("Sub-Cities", "Dreamer Chest Room", 0x1D, 0x05));
            levelDataDict.Add(0x1E00, new LevelData("Ending", "Flutter Launch Area (different)", 0x1E, 0x00));
            levelDataDict.Add(0x1E01, new LevelData("Ending", "Flutter Bridge", 0x1E, 0x01));
            levelDataDict.Add(0x1E02, new LevelData("Ending", "Cliff and Ocean", 0x1E, 0x02));
            levelDataDict.Add(0x1E03, new LevelData("Ending", "Empty?", 0x1E, 0x03));
            levelDataDict.Add(0x1E04, new LevelData("Ending", "Empty?", 0x1E, 0x04));
            levelDataDict.Add(0x1E05, new LevelData("Ending", "Tiny Kattelox", 0x1E, 0x05));
            return levelDataDict;
        }
    }
}
